### ISSUE TITLE
조회된 데이터가 없을때에 undefined error 발생

### ISSUE THREAD

**Issue by aanoaa** [keedi/Parcel-Track-KR-CJKorea#2]
https://www.doortodoor.co.kr/parcel/doortodoor.do?fsp_action=PARC_ACT_002&fsp_cmd=retrieveInvNoACT&invc_no=697617657622

> Can't call method "as_text" on an undefined value at /path/to/Parcel/Track/KR/CJKorea.pm line 109.

``` perl
105:    for my $e (@elements) {
106:        next if $row_index++ == 0;
107:
108:        my @tds = $e->look_down( '_tag', 'td' );
109:        push @{ $result{descs} }, join( q{ }, map $_->as_text, @tds[ 1, 0, 3, 2 ] );
110:
111:        $result{result} = join( q{ }, map $_->as_text, @tds[ 1, 0 ] );
112:    }
```

**Comment by keedi** [comment]
++@aanoaa

Sorry for late response. I've just released [0.005](https://metacpan.org/release/KEEDI/Parcel-Track-KR-CJKorea-0.005).
